
RUNTIME_DATASOURCE_JNDIS = {'jdbc/space/Database1Db' : "database1",
                            'jdbc/area/Database3' : "database3",
                            'jdbc/security/Database2' : "database2"
                            }

CONFIG_INFO = {'localhost': {'environment': 'localhost',
                             'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_localhost',
                                                            'url': 'jdbc:oracle:thin:@//localhost:1521/xe',
                                                            'name': 'Database1Db_localhost',
                                                            'username': 'database1',
                                                            'password': 'database1'},
                                             'database3': {'jndi': 'jdbc/area/Database3_localhost',
                                                           'url': 'jdbc:oracle:thin:@//localhost:1521/xe',
                                                           'name': 'Database3_localhost',
                                                           'username': 'database3',
                                                           'password': 'database3'},
                                             'database4': {'jndi': 'jdbc/fees/Database3_localhost',
                                                     'url': 'jdbc:oracle:thin:@//localhost:1521/xe',
                                                     'name': 'Database4_localhost',
                                                     'username': 'database4',
                                                     'password': 'database4'},
                                             'database2': {'jndi': 'jdbc/security/Database2_localhost',
                                                           'url': 'jdbc:oracle:thin:@//localhost:1521/xe',
                                                           'name': 'Database2_localhost',
                                                           'username': 'database2',
                                                           'password': 'database2'},
                                            }},
               'DEV': {'environment': 'LOCAL',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_dev',
                                                      'url': 'jdbc:oracle:thin:@dev_env.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_dev',
                                                      'username': 'PRJT_DEV_RW_USER',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_dev',
                                                     'url': 'jdbc:oracle:thin:@dev_env.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_dev',
                                                     'username': 'prjt_dev_user2',
                                                     'password': 'user'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_dev',
                                               'url': 'jdbc:oracle:thin:@dev_env.database.priv:1521:database4',
                                               'name': 'Database4',
                                               'username': 'Database4_PRJT_DEV_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_dev',
                                                     'url': 'jdbc:oracle:thin:@dev_env.database.priv:1521:db2_schema',
                                                     'name': 'Database2_dev',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'INT': {'environment': 'STREAM2_INT',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_int',
                                                      'url': 'jdbc:oracle:thin:@int_env.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_int',
                                                      'username': '',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_int',
                                                     'url': 'jdbc:oracle:thin:@int_env.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_int',
                                                     'username': 'PRJT_INT_USER3',
                                                     'password': 'user'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_int',
                                               'url': 'jdbc:oracle:thin:@int_env.database.priv:1521:database4',
                                               'name': 'Database4_int',
                                               'username': 'Database4_PRJT_DEV_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_int',
                                                     'url': 'jdbc:oracle:thin:@int_env.database.priv:1521:ICPUBUAT',
                                                     'name': 'Database2_int',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'QA': {'environment': 'STREAM2_QA',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_qa',
                                                      'url': 'jdbc:oracle:thin:@qa_env.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_qa',
                                                      'username': 'PRJT_QA_RW_USER',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_qa',
                                                     'url': 'jdbc:oracle:thin:@qa_env.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_qa',
                                                     'username': 'PRJT_QA_USER4',
                                                     'password': 'user'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_qa',
                                               'url': 'jdbc:oracle:thin:@qa_env.database.priv:1521:db2_schema',
                                               'name': 'Database4_qa',
                                               'username': 'Database4_PRJT_QA_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_qa',
                                                     'url': 'jdbc:oracle:thin:@qa_env.database.priv:1521:icpubpre',
                                                     'name': 'Database2_qa',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'UAT': {'environment': 'STREAM2_UAT',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_uat',
                                                      'url': 'jdbc:oracle:thin:@uat_env.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_uat',
                                                      'username': 'PRJT_UAT_RW_USER',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_uat',
                                                     'url': 'jdbc:oracle:thin:@uat_env.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_uat',
                                                     'username': 'prjt_uat_user5',
                                                     'password': 'user'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_uat',
                                               'url': 'jdbc:oracle:thin:@uat_env.database.priv:1521:db2_schema',
                                               'name': 'Database4_uat',
                                               'username': 'Database4_PRJT_UAT_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_uat',
                                                     'url': 'jdbc:oracle:thin:@uat_env.database.priv:1521:icpubpre',
                                                     'name': 'Database2_uat',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'DEV_MAINT': {'environment': 'LOCAL',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_dev_maint',
                                                      'url': 'jdbc:oracle:thin:@dev_maint.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_dev_maint',
                                                      'username': 'indwsuser',
                                                      'password': 'indwsdev'},
                                       'database3': {'jndi': 'jdbc/area/Database3_dev_maint',
                                                     'url': 'jdbc:oracle:thin:@dev_maint.database.priv:1521:strtdev',
                                                     'name': 'Database3_dev_maint',
                                                     'username': 'USER',
                                                     'password': 'ecmm_yzw'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_dev_maint',
                                               'url': 'jdbc:oracle:thin:@dev_maint.database.priv:1521:db2_schema',
                                               'name': 'Database4_dev_maint',
                                               'username': 'Database4_PRJT_UAT_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_dev_maint',
                                                     'url': 'jdbc:oracle:thin:@dev_maint.database.priv:1521:db2_schema',
                                                     'name': 'Database2_dev_maint',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'QA_MAINT': {'environment': 'QA',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_qa_maint',
                                                      'url': 'jdbc:oracle:thin:@qa_maint.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_qa_maint',
                                                      'username': 'PRJT_QA_RW_USER',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_qa_maint',
                                                     'url': 'jdbc:oracle:thin:@qa_maint.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_qa_maint',
                                                     'username': 'user',
                                                     'password': 'ecmm_yzw'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_qa_maint',
                                               'url': 'jdbc:oracle:thin:@qa_maint.database.priv:1521:db2_schema',
                                               'name': 'Database4_qa_maint',
                                               'username': 'Database4_MAIN_QA_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_qa_maint',
                                                     'url': 'jdbc:oracle:thin:@qa_maint.database.priv:1521:icpubpre',
                                                     'name': 'Database2_qa_maint',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }},
               'UAT-MAINT': {'environment': 'UAT',
                       'datasources': {'database1': {'jndi': 'jdbc/space/Database1Db_uat_maint',
                                                      'url': 'jdbc:oracle:thin:@uat_maint.database.priv:1521:SCHEMA1',
                                                      'name': 'Database1Db_uat_maint',
                                                      'username': 'MAIN_UAT_RW_USER',
                                                      'password': 'user'},
                                       'database3': {'jndi': 'jdbc/area/Database3_uat_maint',
                                                     'url': 'jdbc:oracle:thin:@uat_maint.database.priv:1521:SCHEMA2',
                                                     'name': 'Database3_uat_maint',
                                                     'username': 'user', 
                                                     'password': 'user'},
                                       'database4': {'jndi': 'jdbc/fees/Database3_uat_maint',
                                               'url': 'jdbc:oracle:thin:@uat_maint.database.priv:db2_schema',
                                               'name': 'Database4_uat_maint',
                                               'username': 'Database4_USER',
                                               'password': 'user'},
                                       'database2': {'jndi': 'jdbc/security/Database2_uat_maint',
                                                     'url': 'jdbc:oracle:thin:@uat_maint.database.priv:1521:testuat',
                                                     'name': 'Database2_uat_maint',
                                                     'username': 'db_user4',
                                                     'password': 'password'},
                                      }}}

ENVIRONMENT_NAME_DICT = {}
for (k,v) in CONFIG_INFO.items():
    ENVIRONMENT_NAME_DICT[v['environment']] = k

JVM_CUSTOM_PROPERTIES = {'BASE_SERVICE_SERVER': 'database.priv',
                         'DESTINATION_ROOT_DIR': '/home/strategy/development',
                         'ENVIRONMENT': 'local',
                         'SERVICES_INTRANET_SERVER': 'localhost:9080',
                         'Default.client.encoding': 'UTF-8',
                         'File.encoding': 'UTF-8',
                         'https.protocols': 'c',
                         'Jsse.enableSNIExtension': 'False',
                         'ws.ext.dirs': '/private/config'}

WEBSPHERE_ENVIRONMENT_VARIABLES = {'ORACLE_JDBC_DRIVER_PATH': 'c:/devtools/oracle/drivers',
                                   'JAVA_HOME': '${JAVA_LOCATION_1.7_64}'}    
